import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider } from 'firebase/auth';
import { initializeFirestore, enableIndexedDbPersistence } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';
import firebaseConfig from '../../firebase-applet-config.json'; // using the JSON in root

console.log('[Firebase Diagnostics] Initializing Firebase with config:', {
  projectId: firebaseConfig.projectId,
  authDomain: firebaseConfig.authDomain,
  hasApiKey: !!firebaseConfig.apiKey,
  apiKeyPrefix: firebaseConfig.apiKey ? `${firebaseConfig.apiKey.substring(0, 6)}...` : 'none',
  appId: firebaseConfig.appId,
});

export const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const googleProvider = new GoogleAuthProvider();
// Explicitly providing the database ID generated by the workspace if not using (default)
const dbId = (firebaseConfig as any).firestoreDatabaseId && (firebaseConfig as any).firestoreDatabaseId !== '(default)'
  ? (firebaseConfig as any).firestoreDatabaseId
  : undefined;

export const db = dbId
  ? initializeFirestore(app, {
      experimentalForceLongPolling: true,
    }, dbId)
  : initializeFirestore(app, {
      experimentalForceLongPolling: true,
    });

if (typeof window !== 'undefined') {
  enableIndexedDbPersistence(db).catch((err) => {
    if (err.code === 'failed-precondition') {
      console.warn('[Firestore Offline Cache] Multiple tabs open. Persistence is enabled in another tab.');
    } else if (err.code === 'unimplemented') {
      console.warn('[Firestore Offline Cache] The current browser does not support persistence.');
    } else {
      console.error('[Firestore Offline Cache] Failed to enable persistence:', err);
    }
  });
}
export const storage = getStorage(app);

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: any;
}

type DbErrorListener = (error: string) => void;
const listeners = new Set<DbErrorListener>();

export function addDbErrorListener(listener: DbErrorListener) {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

export function notifyDbError(errorMessage: string) {
  listeners.forEach(l => {
    try {
      l(errorMessage);
    } catch (e) {
      console.error("Error in DB listener:", e);
    }
  });
}

export function handleFirestoreError(error: any, operationType: OperationType, path: string | null) {
  const errMessage = error instanceof Error ? error.message : String(error);
  
  // Notify any active registered UI banner listeners
  notifyDbError(errMessage);

  const errInfo: FirestoreErrorInfo = {
    error: errMessage,
    authInfo: {
      userId: auth.currentUser?.uid || null,
      email: auth.currentUser?.email || null,
      emailVerified: auth.currentUser?.emailVerified || false,
      isAnonymous: auth.currentUser?.isAnonymous || false,
      tenantId: auth.currentUser?.tenantId || null,
      providerInfo: auth.currentUser?.providerData?.map((provider) => ({
        providerId: provider.providerId,
        email: provider.email || null,
      })) || [],
    },
    operationType,
    path,
  };
  
  console.error('[Firestore Error Managed]', JSON.stringify(errInfo));
  
  // Note: Instead of crashing the whole client application asynchronously (which leads to uncaught exceptions),
  // we do not throw here. This lets React continue operating and showing fallback queries client-side!
}
